FROM node:22-slim

WORKDIR /app

COPY package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm install --registry=https://registry.npmmirror.com

COPY . .

EXPOSE 3100

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
